(** A generic program label.

    The scope of each label is limited to the body of a function.

    Globally-scoped locations, or {b symbols} in our parlance, should
    be referred to by name.

    A label can simply be represented as a number, e.g. [%00001234].

    A more human-readable representation would be [.L1234], as one would
    see in a typical assembly program generated by a compiler.
*)

open Regular.Std

(** A program label. *)
type t

(** The pseudo-entry label. Primarily useful for computing the
    dominator tree of a graph .*)
val pseudoentry : t

(** The pseudo-exit label. Primarily useful for computing the
    dominator tree of a graph .*)
val pseudoexit : t

(** Pretty-prints the label in a more human-readable way. *)
val pp_hum : Format.formatter -> t -> unit

include Regular.S with type t := t
