name: main
run-name: Linting ${{ github.ref }}

on:
  - pull_request

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      OPAMJOBS: 4
      OPAMRETRIES: 8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14.x
          opam-pin: false
          dune-cache: true

      - name: Install dependencies
        run: |
          make deps

      - name: Build cgen
        run: |
          eval $(opam env)
          make

      - name: Run the tests
        run: |
          eval $(opam env)
          make test
